import type { Catalog } from "./types";

export const SAMPLE_CATALOG: Catalog = [
  {
    id: "a001",
    name: "Oak_Door_01",
    type: "StaticMesh",
    path: "/Game/Props/Doors/Oak_Door_01",
    tags: ["tür", "holz", "eiche", "innen"],
    polyCount: 1240,
    sizeMb: 2.1,
    description: "Einfache Eichentür, innen, mit Rahmen.",
  },
  {
    id: "a002",
    name: "Pine_Door_Double",
    type: "StaticMesh",
    path: "/Game/Props/Doors/Pine_Door_Double",
    tags: ["tür", "holz", "kiefer", "außen", "doppelt"],
    polyCount: 2680,
    sizeMb: 3.4,
    description: "Doppelte Kieferntür für Außenbereiche.",
  },
  {
    id: "a003",
    name: "Metal_Door_Industrial",
    type: "StaticMesh",
    path: "/Game/Props/Doors/Metal_Door_Industrial",
    tags: ["tür", "metall", "industrie", "schwer"],
    polyCount: 980,
    sizeMb: 1.8,
    description: "Industrielle Stahltür.",
  },
  {
    id: "a004",
    name: "M_Oak_Wood",
    type: "Material",
    path: "/Game/Materials/Wood/M_Oak_Wood",
    tags: ["material", "holz", "eiche", "braun"],
    sizeMb: 4.2,
    description: "Eichenholz-Material mit Normal Map.",
  },
  {
    id: "a005",
    name: "M_Rusted_Metal",
    type: "Material",
    path: "/Game/Materials/Metal/M_Rusted_Metal",
    tags: ["material", "metall", "rost", "industrie"],
    sizeMb: 3.9,
    description: "Verrostetes Metall-Material.",
  },
  {
    id: "a006",
    name: "T_Brick_Red",
    type: "Texture",
    path: "/Game/Textures/Brick/T_Brick_Red",
    tags: ["textur", "stein", "ziegel", "rot"],
    sizeMb: 8.0,
    description: "Rote Ziegelstein-Textur 2K.",
  },
  {
    id: "a007",
    name: "SM_Rock_Large",
    type: "StaticMesh",
    path: "/Game/Environment/Rocks/SM_Rock_Large",
    tags: ["fels", "stein", "umgebung", "groß"],
    polyCount: 5400,
    sizeMb: 5.5,
    description: "Großer Felsbrocken.",
  },
  {
    id: "a008",
    name: "SM_Rock_Small",
    type: "StaticMesh",
    path: "/Game/Environment/Rocks/SM_Rock_Small",
    tags: ["fels", "stein", "umgebung", "klein"],
    polyCount: 820,
    sizeMb: 1.1,
    description: "Kleiner Felsbrocken.",
  },
  {
    id: "a009",
    name: "BP_Torch",
    type: "Blueprint",
    path: "/Game/Blueprints/Props/BP_Torch",
    tags: ["blueprint", "licht", "fackel", "feuer"],
    sizeMb: 0.6,
    description: "Fackel mit Partikel-Feuer und Lichtquelle.",
  },
  {
    id: "a010",
    name: "P_Fire",
    type: "Particle",
    path: "/Game/Effects/Fire/P_Fire",
    tags: ["partikel", "feuer", "effekt"],
    sizeMb: 2.8,
    description: "Feuer-Partikelsystem.",
  },
  {
    id: "a011",
    name: "SK_Character_Hero",
    type: "SkeletalMesh",
    path: "/Game/Characters/Hero/SK_Character_Hero",
    tags: ["charakter", "held", "skelett", "spieler"],
    polyCount: 18400,
    sizeMb: 12.4,
    description: "Skelett-Mesh des Helden.",
  },
  {
    id: "a012",
    name: "Anim_Idle_Hero",
    type: "Animation",
    path: "/Game/Characters/Hero/Anim/Anim_Idle_Hero",
    tags: ["animation", "idle", "held", "charakter"],
    sizeMb: 0.3,
    description: "Idle-Animation des Helden.",
  },
  {
    id: "a013",
    name: "S_Ambient_Wind",
    type: "Sound",
    path: "/Game/Audio/Ambient/S_Ambient_Wind",
    tags: ["sound", "ambient", "wind", "audio"],
    sizeMb: 6.7,
    description: "Wind-Ambiente-Sound.",
  },
  {
    id: "a014",
    name: "SM_Crate_Wood",
    type: "StaticMesh",
    path: "/Game/Props/Crates/SM_Crate_Wood",
    tags: ["kiste", "holz", "props", "lager"],
    polyCount: 340,
    sizeMb: 0.9,
    description: "Holzkiste.",
  },
  {
    id: "a015",
    name: "SM_Crate_Metal",
    type: "StaticMesh",
    path: "/Game/Props/Crates/SM_Crate_Metal",
    tags: ["kiste", "metall", "props", "lager", "industrie"],
    polyCount: 410,
    sizeMb: 1.0,
    description: "Metallkiste.",
  },
  {
    id: "a016",
    name: "M_Stone_Wet",
    type: "Material",
    path: "/Game/Materials/Stone/M_Stone_Wet",
    tags: ["material", "stein", "nass", "grau"],
    sizeMb: 4.0,
    description: "Nasser Stein.",
  },
];
